### ISSUE TITLE
Texture Issues

### ISSUE THREAD

**Issue by CaptainEivor** [NewJumper/Thats-A-Lot-Of-Items#14]
**Describe the bug**
On 1.18.1 There a texture issue, most of the items are purple and black i will show a photo

**Expected behavior**
Not texture issues

**Screenshots**
![unknown](https://user-images.githubusercontent.com/105654647/168613109-3f7f42d7-9335-481e-b630-eb0caa97d5a7.png)

**Comment by NewJumper** [comment]
Should be fixed in the release 1.18.1-0.14.1 - [here](https://www.curseforge.com/minecraft/mc-mods/thats-a-lot-of-items/files/3794336).
Although, I highly recommend updating to the most recent version on 1.18.2, as I'm not updating any version 1.18.1 or below.
Up to you though!

**Comment by CaptainEivor** [comment]
Yeah, i won't be able to update to 1.18.2 sadly, since most of the mods that i use in my modpack are for 1.18.1
